In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("laptops_dataframe.csv", skipinitialspace=True)

In [3]:
data.head(10)

brand           laptop_name  display_size           processor_type  \
0      HP  Notebook 14-df0008nx         14.00      Intel Celeron N4000   
1  Lenovo    IdeaPad 330S-14IKB         14.00      Intel Core i5-8250U   
2  Huawei      MateBook D Volta         14.00      Intel Core i5-8250U   
3    Dell      Inspiron 15 3567         15.60      Intel Core i3-7020U   
4    Asus    VivoBook 15 X510UR         15.60      Intel Core i7-8550U   
5    Dell           Vostro 5471         14.00      Intel Core i7-8550U   
6   Apple  MacBook Air (Retina)         13.30  Intel Core i5 Dual Core   
7  Huawei            MateBook D         15.60      Intel Core i5-8250U   
8  Huawei        MateBook X Pro         13.88      Intel Core i5-8250U   
9      HP           14-cf0007nx         14.00      Intel Core i5-8250U   

                 graphics_card               disk_space  discount_price  \
0        Intel HD Graphics 600             64 GB (eMMC)          1259.0   
1       Intel UHD Graphics 620                 1 TB HDD          1849.0   
2  NVIDIA GeForce MX150 (2 GB)               256 GB SSD          2999.0   
3        Intel HD Graphics 620                 1 TB HDD          1849.0   
4  NVIDIA GeForce 930MX (2 GB)                 1 TB HDD          2499.0   
5        AMD Radeon 530 (4 GB)      128 GB SSD/1 TB HDD          3799.0   
6       Intel UHD Graphics 617        128 GB (PCIe SSD)          4649.0   
7  NVIDIA GeForce MX150 (2 GB)      128 GB SSD/1 TB HDD          2449.0   
8  NVIDIA GeForce MX150 (2 GB)      256 GB NVMe M.2 SSD          4999.0   
9        AMD Radeon 530 (2 GB)  16 GB (Optane)/1 TB HDD          2629.0   

   old_price ratings_5max  
0     1259.0        0 / 5  
1     2099.0      3.3 / 5  
2     3799.0        0 / 5  
3     1849.0        0 / 5  
4     3149.0        0 / 5  
5     3799.0      3.8 / 5  
6     5199.0      4.0 / 5  
7     2799.0      4.4 / 5  
8     5999.0        0 / 5  
9     2629.0        0 / 5

In [4]:
data.columns.unique()

Index(['brand', 'laptop_name', 'display_size', 'processor_type',
       'graphics_card', 'disk_space', 'discount_price', 'old_price',
       'ratings_5max'],
      dtype='object')

In [16]:
data.drop("ratings_5max",axis=1,inplace=True)

In [17]:
data.head()

brand           laptop_name  display_size       processor_type  \
0      HP  Notebook 14-df0008nx          14.0  Intel Celeron N4000   
1  Lenovo    IdeaPad 330S-14IKB          14.0  Intel Core i5-8250U   
2  Huawei      MateBook D Volta          14.0  Intel Core i5-8250U   
3    Dell      Inspiron 15 3567          15.6  Intel Core i3-7020U   
4    Asus    VivoBook 15 X510UR          15.6  Intel Core i7-8550U   

                 graphics_card    disk_space  discount_price  old_price  
0        Intel HD Graphics 600  64 GB (eMMC)          1259.0     1259.0  
1       Intel UHD Graphics 620      1 TB HDD          1849.0     2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD          2999.0     3799.0  
3        Intel HD Graphics 620      1 TB HDD          1849.0     1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD          2499.0     3149.0

In [18]:
data.drop("discount_price",axis=1,inplace=True)

In [19]:
data.head()

brand           laptop_name  display_size       processor_type  \
0      HP  Notebook 14-df0008nx          14.0  Intel Celeron N4000   
1  Lenovo    IdeaPad 330S-14IKB          14.0  Intel Core i5-8250U   
2  Huawei      MateBook D Volta          14.0  Intel Core i5-8250U   
3    Dell      Inspiron 15 3567          15.6  Intel Core i3-7020U   
4    Asus    VivoBook 15 X510UR          15.6  Intel Core i7-8550U   

                 graphics_card    disk_space  old_price  
0        Intel HD Graphics 600  64 GB (eMMC)     1259.0  
1       Intel UHD Graphics 620      1 TB HDD     2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD     3799.0  
3        Intel HD Graphics 620      1 TB HDD     1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD     3149.0

In [20]:
data.rename(columns = {"old_price":"price"},inplace = True)

In [21]:
data.head()

brand           laptop_name  display_size       processor_type  \
0      HP  Notebook 14-df0008nx          14.0  Intel Celeron N4000   
1  Lenovo    IdeaPad 330S-14IKB          14.0  Intel Core i5-8250U   
2  Huawei      MateBook D Volta          14.0  Intel Core i5-8250U   
3    Dell      Inspiron 15 3567          15.6  Intel Core i3-7020U   
4    Asus    VivoBook 15 X510UR          15.6  Intel Core i7-8550U   

                 graphics_card    disk_space   price  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0  
1       Intel UHD Graphics 620      1 TB HDD  2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0  
3        Intel HD Graphics 620      1 TB HDD  1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0

In [22]:
data["disk_space"].unique()

array(['64 GB (eMMC)', '1 TB HDD', '256 GB SSD', '128 GB SSD/1 TB HDD',
       '128 GB (PCIe SSD)', '256 GB NVMe M.2 SSD',
       '16 GB (Optane)/1 TB HDD', '512 GB SSD', '128 GB (PCIe Flash)',
       '256 GB (PCIe SSD)', '256 GB PCIe NVMe M.2 SSD',
       '256 GB M.2 SSD/1 TB HDD', '128 GB M.2 SSD/1 TB HDD',
       '256 GB NVMe M.2 SSD/1 TB HDD', '256 GB (PCIe Flash)',
       '512 GB NVMe M.2 SSD', '512 GB PCIe NVMe M.2 SSD', '500 GB HDD',
       '2 TB HDD', '128 GB M.2 SSD', '256 GB SSD/1 TB HDD',
       '1 TB PCIe NVMe M.2 SSD', '128 GB SSD', '32 GB (eMMC)', '1 TB SSD',
       '512 GB (PCIe Flash)', '128 GB PCIe NVMe M.2 SSD/1 TB HDD',
       '256 GB SSD (Super Raid)/1 TB HDD', '128 GB PCIe NVMe M.2 SSD',
       '8 GB (Cache Flash)/1 TB HDD'], dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
data["brand"] = labelencoder.fit_transform(data["brand"])

In [24]:
data.head()

brand           laptop_name  display_size       processor_type  \
0      4  Notebook 14-df0008nx          14.0  Intel Celeron N4000   
1      6    IdeaPad 330S-14IKB          14.0  Intel Core i5-8250U   
2      5      MateBook D Volta          14.0  Intel Core i5-8250U   
3      3      Inspiron 15 3567          15.6  Intel Core i3-7020U   
4      2    VivoBook 15 X510UR          15.6  Intel Core i7-8550U   

                 graphics_card    disk_space   price  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0  
1       Intel UHD Graphics 620      1 TB HDD  2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0  
3        Intel HD Graphics 620      1 TB HDD  1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0

In [25]:
data["brand"].unique()

array([4, 6, 5, 3, 2, 1, 0, 8, 7], dtype=int64)

In [26]:
data.rename(columns = {"laptop_name":"return_name"},inplace = True)

In [27]:
data.head()

brand           return_name  display_size       processor_type  \
0      4  Notebook 14-df0008nx          14.0  Intel Celeron N4000   
1      6    IdeaPad 330S-14IKB          14.0  Intel Core i5-8250U   
2      5      MateBook D Volta          14.0  Intel Core i5-8250U   
3      3      Inspiron 15 3567          15.6  Intel Core i3-7020U   
4      2    VivoBook 15 X510UR          15.6  Intel Core i7-8550U   

                 graphics_card    disk_space   price  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0  
1       Intel UHD Graphics 620      1 TB HDD  2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0  
3        Intel HD Graphics 620      1 TB HDD  1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0

In [28]:
data["processor_type"].unique()

array(['Intel Celeron N4000', 'Intel Core i5-8250U',
       'Intel Core i3-7020U', 'Intel Core i7-8550U',
       'Intel Core i5 Dual Core', 'AMD A9-9425', 'Intel Core i7-8565U',
       'Intel Core i7 6 Core', 'Intel Core i5 Quad Core',
       'Intel Core i5-8265U', 'Intel Core M3', 'Intel Core i7-8750H',
       'Intel Core i3-8145U', 'Intel Celeron 4205U',
       'Intel Celeron N3060', 'Intel Celeron N3350',
       'Intel Core i5-7200U', 'Intel Core i9', 'Intel Core i7-7820HK',
       'Intel Core i7-7700HQ', 'Intel Core i7-6700HQ',
       'Intel Core i7 Quad Core', 'Intel Core i7-7500U',
       'Intel Core i3-5005U', 'Intel Core i3-6006U',
       'Intel Core i3-8130U'], dtype=object)

In [29]:
data["processor_type"] = data["processor_type"].map({'Intel Core i7-8565U':7,'AMD A9-9425':7,'Intel Celeron N4000':3,"Intel Core i5-8250U":5,"Intel Core i3-7020U":3,"Intel Core i7-8550U":7,"Intel Core i7-8550U":7,"Intel Core i5 Dual Core":5,'AMD A9-9425':5, 'Intel Core i7-8565U':7, 'Intel Core i7 6 Core':7, 'Intel Core i5 Quad Core':5, 'Intel Core i5-8265U':5, 'Intel Core M3':3, 'Intel Core i7-8750H':7,'Intel Core i3-8145U':3, 'Intel Celeron 4205U':3,'Intel Celeron N3060':3, 'Intel Celeron N3350':3,'Intel Core i5-7200U':5, 'Intel Core i9':9, 'Intel Core i7-7820HK':7,'Intel Core i7-7700HQ':7, 'Intel Core i7-6700HQ':7,'Intel Core i7 Quad Core':7, 'Intel Core i7-7500U':7,'Intel Core i3-5005U':3, 'Intel Core i3-6006U':3,'Intel Core i3-8130U':3})

In [30]:
data.head()

brand           return_name  display_size  processor_type  \
0      4  Notebook 14-df0008nx          14.0               3   
1      6    IdeaPad 330S-14IKB          14.0               5   
2      5      MateBook D Volta          14.0               5   
3      3      Inspiron 15 3567          15.6               3   
4      2    VivoBook 15 X510UR          15.6               7   

                 graphics_card    disk_space   price  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0  
1       Intel UHD Graphics 620      1 TB HDD  2099.0  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0  
3        Intel HD Graphics 620      1 TB HDD  1849.0  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0

In [31]:
data["graphics_card"].unique()

array(['Intel HD Graphics 600', 'Intel UHD Graphics 620',
       'NVIDIA GeForce MX150 (2 GB)', 'Intel HD Graphics 620',
       'NVIDIA GeForce 930MX (2 GB)', 'AMD Radeon 530 (4 GB)',
       'Intel UHD Graphics 617', 'AMD Radeon 530 (2 GB)', 'AMD Radeon R5',
       'Intel GMA HD', 'Intel HD Graphics 6000',
       'Radeon Pro 555X GDDR5 (4 GB)', 'Intel Iris Plus Graphics 655',
       'NVIDIA GeForce MX150 (4 GB)', 'NVIDIA GeForce MX250 (4 GB)',
       'NVIDIA GeForce MX110 (2 GB)', 'NVIDIA GeForce MX230 (2 GB)',
       'Intel HD Graphics 615', 'NVIDIA GeForce MX130 (4 GB)',
       'NVIDIA GeForce GTX 1050 Ti (4 GB)', 'NVIDIA GeForce MX130 (2 GB)',
       'AMD Radeon 520 (2 GB)', 'AMD Radeon 530M (4 GB)',
       'Intel Graphics 620', 'Intel UHD Graphics 600',
       'AMD Radeon 540 (4 GB)', 'NVIDIA GeForce MX250 (2 GB)',
       'NVIDIA GeForce GTX 1050 (3 GB)', 'Intel Iris Plus Graphics 645',
       'Intel HD Graphics 400', 'Intel Iris Plus Graphics 640',
       'Intel HD Graphics 505', 

In [32]:
data["HDD"] = [(1,2)[x == 7] for x in data["processor_type"]]

In [33]:
data.head()

brand           return_name  display_size  processor_type  \
0      4  Notebook 14-df0008nx          14.0               3   
1      6    IdeaPad 330S-14IKB          14.0               5   
2      5      MateBook D Volta          14.0               5   
3      3      Inspiron 15 3567          15.6               3   
4      2    VivoBook 15 X510UR          15.6               7   

                 graphics_card    disk_space   price  HDD  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0    1  
1       Intel UHD Graphics 620      1 TB HDD  2099.0    1  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0    1  
3        Intel HD Graphics 620      1 TB HDD  1849.0    1  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0    2

In [34]:
data["ssd"] = [(256,512)[x==7] for x in data["processor_type"]]

In [35]:
data.head()

brand           return_name  display_size  processor_type  \
0      4  Notebook 14-df0008nx          14.0               3   
1      6    IdeaPad 330S-14IKB          14.0               5   
2      5      MateBook D Volta          14.0               5   
3      3      Inspiron 15 3567          15.6               3   
4      2    VivoBook 15 X510UR          15.6               7   

                 graphics_card    disk_space   price  HDD  ssd  
0        Intel HD Graphics 600  64 GB (eMMC)  1259.0    1  256  
1       Intel UHD Graphics 620      1 TB HDD  2099.0    1  256  
2  NVIDIA GeForce MX150 (2 GB)    256 GB SSD  3799.0    1  256  
3        Intel HD Graphics 620      1 TB HDD  1849.0    1  256  
4  NVIDIA GeForce 930MX (2 GB)      1 TB HDD  3149.0    2  512

In [36]:
data.drop("disk_space",axis=1,inplace=True)

In [37]:
data.head()

brand           return_name  display_size  processor_type  \
0      4  Notebook 14-df0008nx          14.0               3   
1      6    IdeaPad 330S-14IKB          14.0               5   
2      5      MateBook D Volta          14.0               5   
3      3      Inspiron 15 3567          15.6               3   
4      2    VivoBook 15 X510UR          15.6               7   

                 graphics_card   price  HDD  ssd  
0        Intel HD Graphics 600  1259.0    1  256  
1       Intel UHD Graphics 620  2099.0    1  256  
2  NVIDIA GeForce MX150 (2 GB)  3799.0    1  256  
3        Intel HD Graphics 620  1849.0    1  256  
4  NVIDIA GeForce 930MX (2 GB)  3149.0    2  512

In [38]:
data["graphics_card"] = data["graphics_card"].map({'Intel HD Graphics 600':1, 'Intel UHD Graphics 620':2,
       'NVIDIA GeForce MX150 (2 GB)':1, 'Intel HD Graphics 620':1,
       'NVIDIA GeForce 930MX (2 GB)':1, 'AMD Radeon 530 (4 GB)':2,
       'Intel UHD Graphics 617':1, 'AMD Radeon 530 (2 GB)':1, 'AMD Radeon R5':1,
       'Intel GMA HD':1, 'Intel HD Graphics 6000':1,
       'Radeon Pro 555X GDDR5 (4 GB)':2, 'Intel Iris Plus Graphics 655':1,
       'NVIDIA GeForce MX150 (4 GB)':1, 'NVIDIA GeForce MX250 (4 GB)':2,
       'NVIDIA GeForce MX110 (2 GB)':1, 'NVIDIA GeForce MX230 (2 GB)':1,
       'Intel HD Graphics 615':1, 'NVIDIA GeForce MX130 (4 GB)':1,
       'NVIDIA GeForce GTX 1050 Ti (4 GB)':2, 'NVIDIA GeForce MX130 (2 GB)':1,
       'AMD Radeon 520 (2 GB)':1, 'AMD Radeon 530M (4 GB)':2,
       'Intel Graphics 620':1, 'Intel UHD Graphics 600':1,
       'AMD Radeon 540 (4 GB)':2, 'NVIDIA GeForce MX250 (2 GB)':1,
       'NVIDIA GeForce GTX 1050 (3 GB)':2, 'Intel Iris Plus Graphics 645':1,
       'Intel HD Graphics 400':1, 'Intel Iris Plus Graphics 640':1,
       'Intel HD Graphics 505':1, 'Intel HD Graphics 500':1,
       'Radeon Pro 560X GDDR5 (4 GB)':2,
       'NVIDIA GeForce GTX 1080 (8 GB) SLI':3,
       'NVIDIA GeForce GTX 1070 (8 GB)':3, 'NVIDIA GeForce GTX 980M (8 GB)':3,
       'AMD Radeon R9-M370X (2 GB)':2, 'NVIDIA GeForce GTX 1080 (8 GB)':3,
       'NVIDIA GeForce GTX 1050 (4 GB)':2, 'Radeon Pro 555 GDDR5 (2 GB)':1,
       'AMD Radeon 535 (2 GB)':1, 'Intel Iris Pro Graphics':1,
       'Intel Iris Plus Graphics 650':1, 'Intel HD Graphics 520':1,
       'NVIDIA GeForce GT 940MX (2 GB)':1, 'AMD Radeon R5-M340 (2 GB)':1,
       'AMD Radeon R7-M445 (4 GB)':2, 'NVIDIA GeForce 940MX (4 GB)':2,
       'NVIDIA GeForce 940MX (2 GB)':1, 'Intel Iris Graphics 550':1,
       'AMD Radeon R5-M430 (2 GB)':1})

In [39]:
data.head()

brand           return_name  display_size  processor_type  graphics_card  \
0      4  Notebook 14-df0008nx          14.0               3              1   
1      6    IdeaPad 330S-14IKB          14.0               5              2   
2      5      MateBook D Volta          14.0               5              1   
3      3      Inspiron 15 3567          15.6               3              1   
4      2    VivoBook 15 X510UR          15.6               7              1   

    price  HDD  ssd  
0  1259.0    1  256  
1  2099.0    1  256  
2  3799.0    1  256  
3  1849.0    1  256  
4  3149.0    2  512

In [41]:
print("Cleaned data. Success")

Cleaned data. Success


## Here comes the algo

In [43]:
#return_name is not a number so I have to remove it
X = data[[x for x in data.columns if x!="return_name"]]

In [45]:
from sklearn.cluster import KMeans
kmeans_model = KMeans(n_clusters=5)

#Train
kmeans_model.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=5, n_init=10, n_jobs=None, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [46]:
y_kmeans = kmeans_model.predict(X)

In [48]:
y_kmeans

array([0, 0, 3, 0, 3, 3, 2, 3, 2, 0, 0, 2, 3, 2, 4, 3, 1, 1, 2, 2, 2, 3,
       2, 2, 3, 2, 3, 2, 3, 2, 3, 1, 3, 3, 3, 3, 0, 3, 3, 3, 0, 3, 2, 3,
       3, 3, 3, 2, 3, 3, 2, 3, 0, 3, 3, 3, 3, 0, 3, 3, 0, 0, 0, 0, 0, 3,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       0, 0, 0, 0, 3, 3, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2,
       2, 0, 0, 1, 3, 2, 1, 2, 2, 0, 2, 2, 3, 3, 0, 3, 3, 3, 2, 0, 3, 4,
       4, 1, 1, 1, 1, 1, 2, 2, 2, 1, 3, 2, 4, 3, 2, 3, 3, 3, 3, 3, 3, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 3, 0, 3, 2, 3, 3, 3,
       3, 2, 0, 1, 0, 3, 3, 3, 2, 3, 0, 0, 0, 3, 3, 0, 0, 3, 1, 0, 3, 2,
       2, 0, 0, 3, 4, 4, 0])

In [50]:
print("Centroids")
kmeans_model.cluster_centers_

Centroids


array([[3.30434783e+00, 1.50898551e+01, 3.95652174e+00, 1.17391304e+00,
        1.89073913e+03, 1.01449275e+00, 2.59710145e+02],
       [2.06250000e+00, 1.45987500e+01, 6.25000000e+00, 1.56250000e+00,
        8.06649688e+03, 1.62500000e+00, 4.16000000e+02],
       [2.28888889e+00, 1.36084444e+01, 5.66666667e+00, 1.24444444e+00,
        5.76273333e+03, 1.37777778e+00, 3.52711111e+02],
       [3.40579710e+00, 1.46275362e+01, 6.21739130e+00, 1.23188406e+00,
        3.50624638e+03, 1.60869565e+00, 4.11826087e+02],
       [1.00000000e+00, 1.54000000e+01, 7.33333333e+00, 2.00000000e+00,
        1.12490000e+04, 1.83333333e+00, 4.69333333e+02]])

In [65]:
centroid_positions = kmeans_model.cluster_centers_

In [58]:
new_X_centroids = np.zeros((5,5))

In [59]:
new_X_centroids

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
#Setting values randomly for now but
#has to be evaluated by seeing the products
new_X_centroids[0,0] = 1
new_X_centroids[1,1] = 1
new_X_centroids[2,2] = 1
new_X_centroids[3,3] = 1
new_X_centroids[4,4] = 1

In [64]:
new_X_centroids

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
#Diffusion in the data points
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

#Calculate the distance from each centroid
#Simply calculating 1 - norm(dist)
P_centroids = np.zeros((5,5))
for i in range(len(centroid_positions)):
    for j in range(len(centroid_positions)):
        P_centroids[i, j] = sum(np.sqrt((centroid_positions[i] - centroid_positions[j])**2))
    P_centroids[i] = scaler.fit_transform(P_centroids[i].reshape(-1, 1)).reshape(5)
    P_centroids[i] = 1 - P_centroids[i]
    print(P_centroids[i])

[1.         0.33820065 0.58543913 0.81503877 0.        ]
[0.         1.         0.62610219 0.27945032 0.488813  ]
[2.92254554e-01 5.77557083e-01 1.00000000e+00 5.86629464e-01
 1.11022302e-16]
[0.77309728 0.4150089  0.70296356 1.         0.        ]
[0.         0.66169678 0.41425145 0.18484348 1.        ]


In [88]:
#Calculate P value for all the data points
P = []
for ind, val in enumerate(y_kmeans):
    d = sum(np.sqrt((centroid_positions[val] - X.iloc[ind].values)**2))
    P.append(d)

In [93]:
#Here i is the GP
for i in range(5):
    print(P[y_kmeans==i])

TypeError: only integer scalar arrays can be converted to a scalar index

In [5]:
data.shape

(205, 9)

In [8]:
len(data['laptop_name'].unique())

135